plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.kotlin.jvm) apply false
    alias(libs.plugins.kotlin.compose) apply false
    // Lumo UI is a code-generator plugin resolved from Maven Central (not the Gradle Plugin Portal).
    alias(libs.plugins.lumo) apply false
    // ktlint is declared here so the plugin lands on the build classpath once, and
    // applied by each module that owns Kotlin sources (all five). See .editorconfig
    // for the shared style config; all standard rules, including the naming rules,
    // are enabled.
    alias(libs.plugins.ktlint) apply false
}

// ktlint is applied by all five modules, so its SHARED configuration lives here
// once rather than being duplicated into every module script. Two things are
// excluded, and only these two:
//
//  1. `**/build/generated/**` — protobuf/grpc sources generated by the protobuf
//     plugin into `service/build/generated/...`. They are machine output (ktlint
//     1.5.0 flagged 900 violations in them), not authored code, and every
//     `clean` regenerates them. Linting build output is meaningless.
//  2. The vendored Lumo UI kit under `app/.../ui/` — the Lumo Gradle plugin
//     generated `Theme.kt`, `Color.kt`, `Typography.kt`, `components/**` and
//     `foundation/**`. They are vendored third-party generated code; reformatting
//     them would fork them from their generator. The hand-written screens and
//     `*_viewmodel.kt` / `*_state.kt` files stay IN scope and are enforced.
subprojects {
    plugins.withId("org.jlleitschuh.gradle.ktlint") {
        extensions.configure<org.jlleitschuh.gradle.ktlint.KtlintExtension> {
            filter {
                // protobuf/grpc sources generated into `<module>/build/generated/...`
                // are machine output added to :service's Kotlin source set. Ant-style
                // patterns like `**/generated/**` do NOT match them: the plugin builds
                // a multi-root file tree and patterns are matched relative to each
                // root, so the `generated` segment never appears. Match the absolute
                // path instead — that is root-independent and exact.
                exclude(
                    org.gradle.api.specs.Spec<org.gradle.api.file.FileTreeElement> {
                        it.file.path.contains("/build/generated/")
                    },
                )
                exclude(
                    "**/ui/Theme.kt",
                    "**/ui/Color.kt",
                    "**/ui/Typography.kt",
                    "**/ui/components/**",
                    "**/ui/foundation/**",
                )
            }
        }
    }
}

// The T18 E2E gate: one entry point that runs BOTH full-scenario harnesses — the
// plain-JVM hub (`:service`) and the Robolectric-hosted app hub (`:app`). It is a
// thin alias, never a reimplementation, so `./gradlew e2e` and the individual test
// tasks can never diverge.
tasks.register("e2e") {
    group = "verification"
    description = "End-to-end mockpeer integration suites (JVM harness + Robolectric app hub)"
    dependsOn(":service:test", ":app:testDebugUnitTest")
}
