#!/usr/bin/env bash
#
# gen.sh — generate the Go bindings for the frozen `ecosys.v1` contract.
#
# The .proto is owned by :service (service/src/main/proto/ecosys/v1/ecosys.proto).
# This script is the Go half of the codegen: Kotlin lite is generated by the
# protobuf-gradle-plugin inside :service, Go is generated here for the mockpeer.
#
# Idempotent: safe to re-run; it overwrites gen/ with a fresh, deterministic
# result. Exits non-zero on any failure (set -euo pipefail).
#
# Usage:  bash tools/mockpeer/gen.sh
# Env:    PROTOC_VERSION (default 3.25.9 — the same pin :service uses)
#         PROTOC         (path to an existing protoc binary; skips the download)

set -euo pipefail

GoScriptDir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GoRepoRoot="$(cd "$GoScriptDir/../.." && pwd)"
GoProtoRoot="$GoRepoRoot/service/src/main/proto"
GoProtoFile="$GoProtoRoot/ecosys/v1/ecosys.proto"
GoOutDir="$GoScriptDir/gen"
GoProtocDir="$GoScriptDir/.protoc"
GoProtocVersion="${PROTOC_VERSION:-3.25.9}"

if [[ ! -f "$GoProtoFile" ]]; then
	echo "gen.sh: proto not found: $GoProtoFile" >&2
	exit 1
fi

# --- 1. Code generators -------------------------------------------------------
# Pinned to major-compatible lines so the generated code matches the grpc-go /
# protobuf-go versions declared in go.mod. Override with *_VERSION if needed.
GoProtocGenGoVersion="${PROTOC_GEN_GO_VERSION:-latest}"
GoProtocGenGoGrpcVersion="${PROTOC_GEN_GO_GRPC_VERSION:-latest}"

echo "gen.sh: installing protoc-gen-go@$GoProtocGenGoVersion"
go install "google.golang.org/protobuf/cmd/protoc-gen-go@$GoProtocGenGoVersion"
echo "gen.sh: installing protoc-gen-go-grpc@$GoProtocGenGoGrpcVersion"
go install "google.golang.org/grpc/cmd/protoc-gen-go-grpc@$GoProtocGenGoGrpcVersion"

GoBin="$(go env GOPATH)/bin"
export PATH="$GoBin:$PATH"
for GoTool in protoc-gen-go protoc-gen-go-grpc; do
	if ! command -v "$GoTool" >/dev/null 2>&1; then
		echo "gen.sh: $GoTool not on PATH after install (looked in $GoBin)" >&2
		exit 1
	fi
done

# --- 2. protoc binary ---------------------------------------------------------
# Prefer an existing protoc (env override, then PATH); otherwise download the
# prebuilt release into .protoc/ so the script works on a machine with none.
GoProtocBin=""
if [[ -n "${PROTOC:-}" ]]; then
	GoProtocBin="$PROTOC"
elif command -v protoc >/dev/null 2>&1; then
	GoProtocBin="$(command -v protoc)"
fi

if [[ -z "$GoProtocBin" ]]; then
	GoOs="$(uname -s)"
	GoArch="$(uname -m)"
	case "$GoOs" in
	Linux) GoProtocOs="linux" ;;
	Darwin) GoProtocOs="osx" ;;
	*)
		echo "gen.sh: unsupported OS for protoc download: $GoOs (set PROTOC=...)" >&2
		exit 1
		;;
	esac
	case "$GoArch" in
	x86_64 | amd64) GoProtocArch="x86_64" ;;
	aarch64 | arm64) GoProtocArch="aarch_64" ;;
	*)
		echo "gen.sh: unsupported arch for protoc download: $GoArch (set PROTOC=...)" >&2
		exit 1
		;;
	esac
	GoProtocBin="$GoProtocDir/protoc-$GoProtocVersion-$GoProtocOs-$GoProtocArch"
	if [[ ! -x "$GoProtocBin" ]]; then
		mkdir -p "$GoProtocDir"
		# Raw ELF/Mach-O binary, NOT a zip, despite the `.exe` suffix — chmod, don't unzip.
		GoProtocUrl="https://repo1.maven.org/maven2/com/google/protobuf/protoc/$GoProtocVersion/protoc-$GoProtocVersion-$GoProtocOs-$GoProtocArch.exe"
		echo "gen.sh: downloading protoc $GoProtocVersion ($GoProtocOs-$GoProtocArch)"
		curl -fsSL -o "$GoProtocBin" "$GoProtocUrl"
		chmod +x "$GoProtocBin"
	fi
fi

if [[ ! -x "$GoProtocBin" ]]; then
	echo "gen.sh: protoc is not executable: $GoProtocBin" >&2
	exit 1
fi
echo "gen.sh: protoc = $GoProtocBin ($("$GoProtocBin" --version))"

# --- 3. Generate --------------------------------------------------------------
# paths=source_relative keeps the output tree mirroring the proto's own directory
# (ecosys/v1/), independent of the go_package option.
rm -rf "$GoOutDir"
mkdir -p "$GoOutDir"

"$GoProtocBin" \
	-I "$GoProtoRoot" \
	--go_out="$GoOutDir" \
	--go_opt=paths=source_relative \
	--go-grpc_out="$GoOutDir" \
	--go-grpc_opt=paths=source_relative \
	"$GoProtoFile"

# --- 4. Verify ----------------------------------------------------------------
GoPbGo="$(find "$GoOutDir" -name '*.pb.go' | wc -l | tr -d ' ')"
GoGrpcPbGo="$(find "$GoOutDir" -name '*_grpc.pb.go' | wc -l | tr -d ' ')"
if [[ "$GoPbGo" -lt 1 || "$GoGrpcPbGo" -lt 1 ]]; then
	echo "gen.sh: expected *.pb.go and *_grpc.pb.go under $GoOutDir, got pb=$GoPbGo grpc=$GoGrpcPbGo" >&2
	exit 1
fi

# Keep go.sum in sync so `go build ./...` works from a clean checkout.
(cd "$GoScriptDir" && go mod tidy)

echo "gen.sh: OK ($GoPbGo .pb.go, $GoGrpcPbGo _grpc.pb.go)"
find "$GoOutDir" -name '*.go' | sort
